reviewLabelPrefix: r=
reviewers:
  - someone
  - another
numReviewsRequired: 2
numReviewsOverrides:
  tests: 1

mergeScript: bash example-merger.sh

github:
  user: merge-bot
  token: um
  repo: user/repo
  apiBase: https://api.github.com

webhookServerAddr: localhost:2020
